apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: keda-lambda
servers: 1
agents: 2
image: rancher/k3s:latest
ports:
  - port: 4566:30566
    nodeFilters:
      - loadbalancer
  - port: 6379:30379
    nodeFilters:
      - loadbalancer
volumes:
  - volume: /tmp/k3d-localstack:/tmp/localstack
    nodeFilters:
      - server:0
options:
  k3s:
    extraArgs:
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
